"""
Auto-generated template functions for: presentation-template.pptx
Template ID: presentation_template
Generated by: Template Analyzer Tool v2 - Preserves original template design
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from typing import List, Optional
import copy


class PresentationTemplateTemplate:
    """
    Auto-generated template functions
    Template: presentation-template.pptx
    Preserves original design and styling
    """

    def __init__(self, template_path: str):
        """
        Initialize template

        Args:
            template_path: Path to template PPTX file
        """
        # Load the original template with all its design
        self.template_prs = Presentation(template_path)

        # Create new presentation for output
        self.prs = Presentation()

        # Copy slide dimensions from template
        self.prs.slide_width = self.template_prs.slide_width
        self.prs.slide_height = self.template_prs.slide_height

        # Store template slides as references for cloning
        self.template_slides = list(self.template_prs.slides)

        self.template_metadata = {
            "template_id": "presentation_template",
            "template_name": "presentation-template.pptx",
            "template_path": "presentation-template.pptx",
            "slide_width_inches": 10.0,
            "slide_height_inches": 5.625
        }
        self.template_path = template_path

    def _clone_slide_with_layout(self, template_slide_idx: int) -> any:
        """
        Clone a slide from template preserving all background elements

        Args:
            template_slide_idx: Index of template slide to clone (0-based)

        Returns:
            New slide with cloned background
        """
        if template_slide_idx >= len(self.template_slides):
            template_slide_idx = 0  # Default to first slide

        template_slide = self.template_slides[template_slide_idx]

        # Add blank slide to presentation
        blank_layout = self.prs.slide_layouts[0]
        new_slide = self.prs.slides.add_slide(blank_layout)

        # Clone all shapes from template slide except text content
        for shape in template_slide.shapes:
            # Skip if it's a text shape we'll replace
            if hasattr(shape, "text") and shape.text in [
                "Presentation Title", "Subtitle or Tagline Goes Here",
                "Section Title", "Content Slide Title", "01", "02", "03", "04", "05"
            ]:
                continue

            # Clone the shape
            try:
                el = shape.element
                newel = copy.deepcopy(el)
                new_slide.shapes._spTree.insert_element_before(newel, 'p:extLst')
            except:
                pass  # Skip if can't clone

        return new_slide

    def add_title_slide(self, title: str, subtitle: str = None) -> None:
        """
        Add title slide using template design (Slide 1 style)

        Args:
            title: Main title text
            subtitle: Subtitle text (optional)
        """
        slide = self._clone_slide_with_layout(0)  # Clone from slide 1

        # Add title text (white, large, bold)
        title_box = slide.shapes.add_textbox(
            Inches(2.87), Inches(1.96),
            Inches(4.27), Inches(0.5)
        )
        title_frame = title_box.text_frame
        title_frame.text = title
        title_para = title_frame.paragraphs[0]
        title_para.font.name = "Arial"
        title_para.font.size = Pt(36)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(255, 255, 255)  # White
        title_para.alignment = PP_ALIGN.LEFT

        # Add subtitle if provided (light gray)
        if subtitle:
            subtitle_box = slide.shapes.add_textbox(
                Inches(3.06), Inches(3.25),
                Inches(3.88), Inches(0.41)
            )
            subtitle_frame = subtitle_box.text_frame
            subtitle_frame.text = subtitle
            subtitle_para = subtitle_frame.paragraphs[0]
            subtitle_para.font.name = "Arial"
            subtitle_para.font.size = Pt(21)
            subtitle_para.font.color.rgb = RGBColor(236, 240, 241)  # Light gray
            subtitle_para.alignment = PP_ALIGN.LEFT

    def add_content_slide(self, title: str, bullets: List[str]) -> None:
        """
        Add bullet point slide using template design (Slide 3 style)

        Args:
            title: Slide title
            bullets: List of bullet points
        """
        slide = self._clone_slide_with_layout(2)  # Clone from slide 3 (content slide)

        # Add title (dark color, bold)
        title_box = slide.shapes.add_textbox(
            Inches(0.63), Inches(1.06),
            Inches(4.47), Inches(0.37)
        )
        title_frame = title_box.text_frame
        title_frame.text = title
        title_para = title_frame.paragraphs[0]
        title_para.font.name = "Arial"
        title_para.font.size = Pt(24)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(28, 40, 51)  # Dark color

        # Add bullets (dark gray)
        content_top = Inches(1.68)
        line_height = Inches(0.30)

        for i, bullet in enumerate(bullets[:6]):  # Max 6 bullets
            bullet_box = slide.shapes.add_textbox(
                Inches(0.63), content_top + (line_height * i),
                Inches(8.93), line_height
            )
            bullet_frame = bullet_box.text_frame
            bullet_frame.text = f"• {bullet}"
            bullet_para = bullet_frame.paragraphs[0]
            bullet_para.font.name = "Arial"
            bullet_para.font.size = Pt(14)
            bullet_para.font.color.rgb = RGBColor(44, 62, 80)  # Dark gray

    def add_section_header_slide(self, title: str, section_number: str = "01") -> None:
        """
        Add section header slide using template design (Slide 2 style)

        Args:
            title: Section title
            section_number: Section number (e.g., "01", "02")
        """
        slide = self._clone_slide_with_layout(1)  # Clone from slide 2

        # Add large section number (blue)
        number_box = slide.shapes.add_textbox(
            Inches(4.58), Inches(2.38),
            Inches(0.85), Inches(1.05)
        )
        number_frame = number_box.text_frame
        number_frame.text = section_number
        number_para = number_frame.paragraphs[0]
        number_para.font.name = "Arial"
        number_para.font.size = Pt(54)
        number_para.font.bold = True
        number_para.font.color.rgb = RGBColor(52, 152, 219)  # Blue accent

        # Add section title (dark, bold)
        title_box = slide.shapes.add_textbox(
            Inches(3.68), Inches(3.68),
            Inches(2.65), Inches(0.44)
        )
        title_frame = title_box.text_frame
        title_frame.text = title
        title_para = title_frame.paragraphs[0]
        title_para.font.name = "Arial"
        title_para.font.size = Pt(32)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(28, 40, 51)  # Dark

    def add_image_placeholder_slide(self, title: str, image_prompt: str,
                                     context: str = None) -> None:
        """
        Add slide with image placeholder showing prompt

        Args:
            title: Slide title
            image_prompt: AI-generated image prompt to display
            context: Optional context about why this image
        """
        slide = self._clone_slide_with_layout(2)  # Use content slide style

        # Add title (dark color, bold)
        title_box = slide.shapes.add_textbox(
            Inches(0.63), Inches(1.06),
            Inches(4.47), Inches(0.37)
        )
        title_frame = title_box.text_frame
        title_frame.text = title
        title_para = title_frame.paragraphs[0]
        title_para.font.name = "Arial"
        title_para.font.size = Pt(24)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(28, 40, 51)

        # Add image placeholder box with blue theme
        placeholder_box = slide.shapes.add_shape(
            1,  # Rectangle
            Inches(1.5), Inches(2.0),
            Inches(7.0), Inches(2.5)
        )

        # Style with template colors
        placeholder_box.fill.solid()
        placeholder_box.fill.fore_color.rgb = RGBColor(232, 244, 248)  # Light blue
        placeholder_box.line.color.rgb = RGBColor(52, 152, 219)  # Blue accent
        placeholder_box.line.width = Pt(3)

        # Add prompt text
        text_frame = placeholder_box.text_frame
        text_frame.word_wrap = True
        text_frame.margin_left = Inches(0.3)
        text_frame.margin_right = Inches(0.3)
        text_frame.margin_top = Inches(0.2)

        # Header
        p1 = text_frame.paragraphs[0]
        p1.text = "IMAGE PROMPT:"
        p1.font.name = "Arial"
        p1.font.size = Pt(12)
        p1.font.bold = True
        p1.font.color.rgb = RGBColor(52, 152, 219)  # Blue

        # Prompt
        p2 = text_frame.add_paragraph()
        p2.text = image_prompt
        p2.font.name = "Arial"
        p2.font.size = Pt(10)
        p2.space_before = Pt(10)
        p2.font.color.rgb = RGBColor(44, 62, 80)  # Dark gray

    def add_two_column_slide(self, title: str, left_content: List[str],
                            right_content: List[str]) -> None:
        """
        Add two-column comparison slide

        Args:
            title: Slide title
            left_content: Left column bullet points
            right_content: Right column bullet points
        """
        slide = self._clone_slide_with_layout(2)

        # Add title
        title_box = slide.shapes.add_textbox(
            Inches(0.63), Inches(1.06),
            Inches(4.47), Inches(0.37)
        )
        title_frame = title_box.text_frame
        title_frame.text = title
        title_para = title_frame.paragraphs[0]
        title_para.font.name = "Arial"
        title_para.font.size = Pt(24)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(28, 40, 51)

        # Left column
        left_box = slide.shapes.add_textbox(
            Inches(0.63), Inches(1.68),
            Inches(4.0), Inches(2.8)
        )
        left_frame = left_box.text_frame
        left_frame.word_wrap = True
        for item in left_content:
            p = left_frame.add_paragraph()
            p.text = f"• {item}"
            p.font.name = "Arial"
            p.font.size = Pt(12)
            p.font.color.rgb = RGBColor(44, 62, 80)

        # Right column
        right_box = slide.shapes.add_textbox(
            Inches(5.0), Inches(1.68),
            Inches(4.0), Inches(2.8)
        )
        right_frame = right_box.text_frame
        right_frame.word_wrap = True
        for item in right_content:
            p = right_frame.add_paragraph()
            p.text = f"• {item}"
            p.font.name = "Arial"
            p.font.size = Pt(12)
            p.font.color.rgb = RGBColor(44, 62, 80)

    def save(self, output_path: str) -> str:
        """
        Save the presentation

        Args:
            output_path: Path to save PPTX file

        Returns:
            Saved file path
        """
        self.prs.save(output_path)
        return output_path

    def get_slide_count(self) -> int:
        """Get current number of slides"""
        return len(self.prs.slides)
