"""
Auto-generated template functions for: presentation-template.pptx
Template ID: presentation_template
Generated by: Template Analyzer Tool
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from typing import List, Optional


class PresentationTemplateTemplate:
    """
    Auto-generated template functions
    Template: presentation-template.pptx
    """

    def __init__(self, template_path: str):
        """
        Initialize template

        Args:
            template_path: Path to template PPTX file
        """
        # Load template to get layouts, but start with clean presentation
        template_prs = Presentation(template_path)

        # Create new presentation using the template's slide masters
        self.prs = Presentation(template_path)

        # Remove all existing slides from template
        while len(self.prs.slides) > 0:
            rId = self.prs.slides._sldIdLst[0].rId
            self.prs.part.drop_rel(rId)
            del self.prs.slides._sldIdLst[0]

        self.template_metadata = {
        "template_id": "presentation_template",
        "template_name": "presentation-template.pptx",
        "template_path": "presentation-template.pptx",
        "slide_width_inches": 10.0,
        "slide_height_inches": 5.625,
        "layouts": [
                {
                        "layout_id": "layout_0",
                        "layout_index": 0,
                        "layout_name": "DEFAULT",
                        "slots": {},
                        "total_shapes": 0
                }
        ]
}
        self.template_path = template_path

    def add_title_slide(self, title: str, subtitle: str = None) -> None:
        """
        Add title slide

        Args:
            title: Main title text
            subtitle: Subtitle text (optional)
        """
        layout = self.prs.slide_layouts[0]
        slide = self.prs.slides.add_slide(layout)

        # Add title as text box
        title_box = slide.shapes.add_textbox(
            Inches(1), Inches(2),
            Inches(8), Inches(1)
        )
        title_frame = title_box.text_frame
        title_frame.text = title
        title_frame.paragraphs[0].font.size = Pt(44)
        title_frame.paragraphs[0].font.bold = True
        title_frame.paragraphs[0].alignment = PP_ALIGN.CENTER

        # Add subtitle if provided
        if subtitle:
            subtitle_box = slide.shapes.add_textbox(
                Inches(1), Inches(3.2),
                Inches(8), Inches(0.8)
            )
            subtitle_frame = subtitle_box.text_frame
            subtitle_frame.text = subtitle
            subtitle_frame.paragraphs[0].font.size = Pt(24)
            subtitle_frame.paragraphs[0].alignment = PP_ALIGN.CENTER

    def add_content_slide(self, title: str, bullets: List[str]) -> None:
        """
        Add bullet point slide

        Args:
            title: Slide title
            bullets: List of bullet points
        """
        # Use layout 1 if available, otherwise layout 0
        layout_idx = min(1, len(self.prs.slide_layouts) - 1)
        layout = self.prs.slide_layouts[layout_idx]
        slide = self.prs.slides.add_slide(layout)

        # Add title as text box if no title placeholder
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(0.5),
            Inches(9), Inches(0.8)
        )
        title_frame = title_box.text_frame
        title_frame.text = title
        title_frame.paragraphs[0].font.size = Pt(32)
        title_frame.paragraphs[0].font.bold = True

        # Add bullets as text box
        content_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(1.5),
            Inches(9), Inches(4)
        )
        text_frame = content_box.text_frame
        text_frame.word_wrap = True

        for bullet in bullets:
            p = text_frame.add_paragraph()
            p.text = str(bullet)
            p.level = 0
            p.font.size = Pt(18)

    def add_section_header_slide(self, title: str) -> None:
        """
        Add section header slide

        Args:
            title: Section title
        """
        # Try to find section header layout (often layout 2 or 3)
        layout_idx = min(2, len(self.prs.slide_layouts) - 1)
        layout = self.prs.slide_layouts[layout_idx]
        slide = self.prs.slides.add_slide(layout)

        if slide.shapes.title:
            slide.shapes.title.text = title

    def add_image_placeholder_slide(self, title: str, image_prompt: str,
                                     context: str = None) -> None:
        """
        Add slide with image placeholder showing prompt

        Args:
            title: Slide title
            image_prompt: AI-generated image prompt to display
            context: Optional context about why this image
        """
        # Use blank or content layout
        layout_idx = min(5, len(self.prs.slide_layouts) - 1)
        layout = self.prs.slide_layouts[layout_idx]
        slide = self.prs.slides.add_slide(layout)

        # Add title box
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(0.5),
            Inches(9), Inches(0.8)
        )
        title_frame = title_box.text_frame
        title_frame.text = title
        title_frame.paragraphs[0].font.size = Pt(32)
        title_frame.paragraphs[0].font.bold = True

        # Add image placeholder box
        placeholder_box = slide.shapes.add_shape(
            1,  # Rectangle (MSO_SHAPE.RECTANGLE)
            Inches(1.5), Inches(2),
            Inches(7), Inches(4)
        )

        # Style the placeholder
        placeholder_box.fill.solid()
        placeholder_box.fill.fore_color.rgb = RGBColor(232, 244, 248)  # Light blue
        placeholder_box.line.color.rgb = RGBColor(30, 58, 138)  # Dark blue
        placeholder_box.line.width = Pt(2)

        # Add prompt text inside placeholder
        text_frame = placeholder_box.text_frame
        text_frame.word_wrap = True
        text_frame.margin_left = Inches(0.3)
        text_frame.margin_right = Inches(0.3)
        text_frame.margin_top = Inches(0.3)

        # Header
        p1 = text_frame.paragraphs[0]
        p1.text = "📷 IMAGE PROMPT:"
        p1.font.size = Pt(14)
        p1.font.bold = True
        p1.font.color.rgb = RGBColor(30, 58, 138)

        # Prompt text
        p2 = text_frame.add_paragraph()
        p2.text = image_prompt
        p2.font.size = Pt(11)
        p2.space_before = Pt(12)
        p2.font.color.rgb = RGBColor(0, 0, 0)

        # Context if provided
        if context:
            p3 = text_frame.add_paragraph()
            p3.text = f"\n💡 Context: {context}"
            p3.font.size = Pt(10)
            p3.font.italic = True
            p3.space_before = Pt(12)
            p3.font.color.rgb = RGBColor(75, 85, 99)

    def add_two_column_slide(self, title: str, left_content: List[str],
                            right_content: List[str]) -> None:
        """
        Add two-column comparison slide

        Args:
            title: Slide title
            left_content: Left column bullet points
            right_content: Right column bullet points
        """
        # Use any available layout
        layout = self.prs.slide_layouts[0]
        slide = self.prs.slides.add_slide(layout)

        # Add title
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(0.5),
            Inches(9), Inches(0.8)
        )
        title_frame = title_box.text_frame
        title_frame.text = title
        title_frame.paragraphs[0].font.size = Pt(32)
        title_frame.paragraphs[0].font.bold = True

        # Add two text boxes
        left_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(1.5),
            Inches(4.5), Inches(4)
        )
        right_box = slide.shapes.add_textbox(
            Inches(5), Inches(1.5),
            Inches(4.5), Inches(4)
        )

        # Fill left column
        left_frame = left_box.text_frame
        left_frame.word_wrap = True
        for item in left_content:
            p = left_frame.add_paragraph()
            p.text = str(item)
            p.font.size = Pt(14)

        # Fill right column
        right_frame = right_box.text_frame
        right_frame.word_wrap = True
        for item in right_content:
            p = right_frame.add_paragraph()
            p.text = str(item)
            p.font.size = Pt(14)

    def save(self, output_path: str) -> str:
        """
        Save the presentation

        Args:
            output_path: Path to save PPTX file

        Returns:
            Saved file path
        """
        self.prs.save(output_path)
        return output_path

    def get_slide_count(self) -> int:
        """Get current number of slides"""
        return len(self.prs.slides)
